/* Generated by re2c 0.16 on Fri Nov 23 14:19:44 2018 */
#line 1 "lua-parser.re2c"
typedef struct LuaScanner {
  char *top, *last_top, *cur, *ptr, *pos, *limit;
  int line;
} LuaScanner;

#define   YYCTYPE     unsigned char
#define   YYCURSOR    s->cur
#define   YYMARKER    s->ptr
#define   YYLIMIT    s->limit

static void processNewLine(LuaScanner* s)
{
  //printf("%d:%.25s\n", s->line, s->top);
  s->pos = s->cur;
  s->line++;
}

static int scan(LuaScanner* s, char *buff_end) {

  int nest_count = 0;

regular:
  if (s->cur >= buff_end) {
    return TK_THEEND;
  }
  s->top = s->cur;

#line 51 "lua-parser.re2c"



#line 35 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '"':	goto yy10;
	case '#':	goto yy11;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '\'':	goto yy17;
	case '(':	goto yy18;
	case ')':	goto yy20;
	case '*':	goto yy22;
	case '+':	goto yy24;
	case ',':	goto yy26;
	case '-':	goto yy28;
	case '.':	goto yy30;
	case '/':	goto yy32;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case ':':	goto yy37;
	case ';':	goto yy39;
	case '<':	goto yy41;
	case '=':	goto yy43;
	case '>':	goto yy45;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'c':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'p':
	case 'q':
	case 's':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	case '[':	goto yy50;
	case ']':	goto yy52;
	case '^':	goto yy54;
	case 'a':	goto yy56;
	case 'b':	goto yy57;
	case 'd':	goto yy58;
	case 'e':	goto yy59;
	case 'f':	goto yy60;
	case 'g':	goto yy61;
	case 'i':	goto yy62;
	case 'l':	goto yy63;
	case 'n':	goto yy64;
	case 'o':	goto yy65;
	case 'r':	goto yy66;
	case 't':	goto yy67;
	case 'u':	goto yy68;
	case 'w':	goto yy69;
	case '{':	goto yy70;
	case '|':	goto yy72;
	case '}':	goto yy74;
	case '~':	goto yy76;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 150 "lua-parser.re2c"
	{ goto regular; }
#line 142 "lua-parser.re2c.c"
yy4:
	++YYCURSOR;
yy5:
#line 144 "lua-parser.re2c"
	{ fprintf(stderr, "unexpected character: '%c' at line %d:%d\n",
                        *s->cur, s->line, (int)(s->cur - s->pos));
                        exit(1);
                    }
#line 151 "lua-parser.re2c.c"
yy6:
	++YYCURSOR;
#line 57 "lua-parser.re2c"
	{ goto regular; }
#line 156 "lua-parser.re2c.c"
yy8:
	++YYCURSOR;
#line 56 "lua-parser.re2c"
	{ processNewLine(s); goto regular; }
#line 161 "lua-parser.re2c.c"
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy79;
yy11:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '!':	goto yy84;
	default:	goto yy12;
	}
yy12:
#line 95 "lua-parser.re2c"
	{ return TK_LEN; }
#line 176 "lua-parser.re2c.c"
yy13:
	++YYCURSOR;
#line 93 "lua-parser.re2c"
	{ return TK_MOD; }
#line 181 "lua-parser.re2c.c"
yy15:
	++YYCURSOR;
#line 114 "lua-parser.re2c"
	{ return TK_BITAND; }
#line 186 "lua-parser.re2c.c"
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy88;
yy18:
	++YYCURSOR;
#line 123 "lua-parser.re2c"
	{ return TK_LPAREN; }
#line 196 "lua-parser.re2c.c"
yy20:
	++YYCURSOR;
#line 124 "lua-parser.re2c"
	{ return TK_RPAREN; }
#line 201 "lua-parser.re2c.c"
yy22:
	++YYCURSOR;
#line 92 "lua-parser.re2c"
	{ return TK_MUL; }
#line 206 "lua-parser.re2c.c"
yy24:
	++YYCURSOR;
#line 89 "lua-parser.re2c"
	{ return TK_PLUS; }
#line 211 "lua-parser.re2c.c"
yy26:
	++YYCURSOR;
#line 100 "lua-parser.re2c"
	{ return TK_COMMA; }
#line 216 "lua-parser.re2c.c"
yy28:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy92;
	default:	goto yy29;
	}
yy29:
#line 90 "lua-parser.re2c"
	{ return TK_MINUS; }
#line 226 "lua-parser.re2c.c"
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy94;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	default:	goto yy31;
	}
yy31:
#line 122 "lua-parser.re2c"
	{ return TK_DOT; }
#line 246 "lua-parser.re2c.c"
yy32:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy98;
	default:	goto yy33;
	}
yy33:
#line 91 "lua-parser.re2c"
	{ return TK_DIV; }
#line 256 "lua-parser.re2c.c"
yy34:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy96;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy36;
	}
yy36:
#line 135 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 280 "lua-parser.re2c.c"
yy37:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ':':	goto yy101;
	default:	goto yy38;
	}
yy38:
#line 121 "lua-parser.re2c"
	{ return TK_COLON; }
#line 291 "lua-parser.re2c.c"
yy39:
	++YYCURSOR;
#line 120 "lua-parser.re2c"
	{ return TK_SEMICOLON; }
#line 296 "lua-parser.re2c.c"
yy41:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '<':	goto yy102;
	case '=':	goto yy104;
	default:	goto yy42;
	}
yy42:
#line 98 "lua-parser.re2c"
	{ return TK_LT; }
#line 307 "lua-parser.re2c.c"
yy43:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy106;
	default:	goto yy44;
	}
yy44:
#line 88 "lua-parser.re2c"
	{ return TK_ASSIGN; }
#line 317 "lua-parser.re2c.c"
yy45:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy108;
	case '>':	goto yy110;
	default:	goto yy46;
	}
yy46:
#line 99 "lua-parser.re2c"
	{ return TK_BT; }
#line 328 "lua-parser.re2c.c"
yy47:
	++YYCURSOR;
	yych = *YYCURSOR;
yy48:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy49;
	}
yy49:
#line 132 "lua-parser.re2c"
	{ return TK_NAME; }
#line 402 "lua-parser.re2c.c"
yy50:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '[':	goto yy112;
	default:	goto yy51;
	}
yy51:
#line 127 "lua-parser.re2c"
	{ return TK_LBRACKET; }
#line 412 "lua-parser.re2c.c"
yy52:
	++YYCURSOR;
#line 128 "lua-parser.re2c"
	{ return TK_RBRACKET; }
#line 417 "lua-parser.re2c.c"
yy54:
	++YYCURSOR;
#line 94 "lua-parser.re2c"
	{ return TK_POW; }
#line 422 "lua-parser.re2c.c"
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy114;
	default:	goto yy48;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy115;
	default:	goto yy48;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy116;
	default:	goto yy48;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy118;
	case 'n':	goto yy119;
	default:	goto yy48;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy120;
	case 'o':	goto yy121;
	case 'u':	goto yy122;
	default:	goto yy48;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy123;
	default:	goto yy48;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy124;
	case 'n':	goto yy126;
	default:	goto yy48;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy128;
	default:	goto yy48;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy129;
	case 'o':	goto yy130;
	default:	goto yy48;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy131;
	default:	goto yy48;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy133;
	default:	goto yy48;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy134;
	case 'r':	goto yy135;
	default:	goto yy48;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy136;
	default:	goto yy48;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy137;
	default:	goto yy48;
	}
yy70:
	++YYCURSOR;
#line 125 "lua-parser.re2c"
	{ return TK_LBRACE; }
#line 517 "lua-parser.re2c.c"
yy72:
	++YYCURSOR;
#line 113 "lua-parser.re2c"
	{ return TK_BITOR; }
#line 522 "lua-parser.re2c.c"
yy74:
	++YYCURSOR;
#line 126 "lua-parser.re2c"
	{ return TK_RBRACE; }
#line 527 "lua-parser.re2c.c"
yy76:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy138;
	default:	goto yy77;
	}
yy77:
#line 112 "lua-parser.re2c"
	{ return TK_BITNOT; }
#line 537 "lua-parser.re2c.c"
yy78:
	++YYCURSOR;
	yych = *YYCURSOR;
yy79:
	switch (yych) {
	case 0x00:	goto yy80;
	case '"':	goto yy81;
	case '\\':	goto yy83;
	default:	goto yy78;
	}
yy80:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy36;
	case 2: 	goto yy38;
	default:	goto yy93;
	}
yy81:
	++YYCURSOR;
#line 137 "lua-parser.re2c"
	{ return TK_STRING; }
#line 560 "lua-parser.re2c.c"
yy83:
	++YYCURSOR;
	yych = *YYCURSOR;
	if (yych <= 0x00) goto yy80;
	goto yy78;
yy84:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy86;
	default:	goto yy84;
	}
yy86:
#line 140 "lua-parser.re2c"
	{ goto regular; }
#line 577 "lua-parser.re2c.c"
yy87:
	++YYCURSOR;
	yych = *YYCURSOR;
yy88:
	switch (yych) {
	case 0x00:	goto yy80;
	case '\'':	goto yy89;
	case '\\':	goto yy91;
	default:	goto yy87;
	}
yy89:
	++YYCURSOR;
#line 136 "lua-parser.re2c"
	{ return TK_STRING; }
#line 592 "lua-parser.re2c.c"
yy91:
	++YYCURSOR;
	yych = *YYCURSOR;
	if (yych <= 0x00) goto yy80;
	goto yy87;
yy92:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '[':	goto yy140;
	default:	goto yy93;
	}
yy93:
#line 61 "lua-parser.re2c"
	{ goto Comment; }
#line 608 "lua-parser.re2c.c"
yy94:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy141;
	default:	goto yy95;
	}
yy95:
#line 97 "lua-parser.re2c"
	{ return TK_CONCAT; }
#line 618 "lua-parser.re2c.c"
yy96:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy36;
	}
yy98:
	++YYCURSOR;
#line 108 "lua-parser.re2c"
	{ return TK_IDIV; }
#line 642 "lua-parser.re2c.c"
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy143;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy144;
	default:	goto yy80;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':	goto yy80;
	default:	goto yy147;
	}
yy102:
	++YYCURSOR;
#line 115 "lua-parser.re2c"
	{ return TK_SHL; }
#line 680 "lua-parser.re2c.c"
yy104:
	++YYCURSOR;
#line 103 "lua-parser.re2c"
	{ return TK_LTEQ; }
#line 685 "lua-parser.re2c.c"
yy106:
	++YYCURSOR;
#line 101 "lua-parser.re2c"
	{ return TK_EQ; }
#line 690 "lua-parser.re2c.c"
yy108:
	++YYCURSOR;
#line 102 "lua-parser.re2c"
	{ return TK_BTEQ; }
#line 695 "lua-parser.re2c.c"
yy110:
	++YYCURSOR;
#line 116 "lua-parser.re2c"
	{ return TK_SHR; }
#line 700 "lua-parser.re2c.c"
yy112:
	++YYCURSOR;
#line 129 "lua-parser.re2c"
	{ nest_count=0; goto LongString; }
#line 705 "lua-parser.re2c.c"
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy148;
	default:	goto yy48;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy150;
	default:	goto yy48;
	}
yy116:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy117;
	}
yy117:
#line 66 "lua-parser.re2c"
	{ return TK_DO; }
#line 789 "lua-parser.re2c.c"
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy151;
	default:	goto yy48;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy152;
	default:	goto yy48;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy154;
	default:	goto yy48;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy155;
	default:	goto yy48;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy157;
	default:	goto yy48;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy158;
	default:	goto yy48;
	}
yy124:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy125;
	}
yy125:
#line 74 "lua-parser.re2c"
	{ return TK_IF; }
#line 897 "lua-parser.re2c.c"
yy126:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy127;
	}
yy127:
#line 75 "lua-parser.re2c"
	{ return TK_IN; }
#line 969 "lua-parser.re2c.c"
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy159;
	default:	goto yy48;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy160;
	default:	goto yy48;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy162;
	default:	goto yy48;
	}
yy131:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy132;
	}
yy132:
#line 79 "lua-parser.re2c"
	{ return TK_OR; }
#line 1059 "lua-parser.re2c.c"
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy164;
	case 't':	goto yy165;
	default:	goto yy48;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy166;
	default:	goto yy48;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy167;
	default:	goto yy48;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy168;
	default:	goto yy48;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy169;
	default:	goto yy48;
	}
yy138:
	++YYCURSOR;
#line 104 "lua-parser.re2c"
	{ return TK_NEQ; }
#line 1095 "lua-parser.re2c.c"
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case '[':	goto yy170;
	default:	goto yy80;
	}
yy141:
	++YYCURSOR;
#line 96 "lua-parser.re2c"
	{ return TK_ELLIPSIS; }
#line 1106 "lua-parser.re2c.c"
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy144;
	default:	goto yy80;
	}
yy144:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy144;
	default:	goto yy36;
	}
yy146:
	++YYCURSOR;
	yych = *YYCURSOR;
yy147:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy146;
	case ':':	goto yy172;
	default:	goto yy80;
	}
yy148:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy149;
	}
yy149:
#line 64 "lua-parser.re2c"
	{ return TK_AND; }
#line 1280 "lua-parser.re2c.c"
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy173;
	default:	goto yy48;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy174;
	default:	goto yy48;
	}
yy152:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy153;
	}
yy153:
#line 69 "lua-parser.re2c"
	{ return TK_END; }
#line 1364 "lua-parser.re2c.c"
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy176;
	default:	goto yy48;
	}
yy155:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy156;
	}
yy156:
#line 71 "lua-parser.re2c"
	{ return TK_FOR; }
#line 1442 "lua-parser.re2c.c"
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy177;
	default:	goto yy48;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy178;
	default:	goto yy48;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy180;
	default:	goto yy48;
	}
yy160:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy161;
	}
yy161:
#line 77 "lua-parser.re2c"
	{ return TK_NIL; }
#line 1532 "lua-parser.re2c.c"
yy162:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy163;
	}
yy163:
#line 78 "lua-parser.re2c"
	{ return TK_NOT; }
#line 1604 "lua-parser.re2c.c"
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy181;
	default:	goto yy48;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy182;
	default:	goto yy48;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy183;
	default:	goto yy48;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy185;
	default:	goto yy48;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy187;
	default:	goto yy48;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy188;
	default:	goto yy48;
	}
yy170:
	++YYCURSOR;
#line 60 "lua-parser.re2c"
	{ nest_count=0; goto LongComment; }
#line 1645 "lua-parser.re2c.c"
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy189;
	default:	goto yy80;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy191;
	default:	goto yy48;
	}
yy174:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	case 'i':	goto yy193;
	default:	goto yy175;
	}
yy175:
#line 67 "lua-parser.re2c"
	{ return TK_ELSE; }
#line 1729 "lua-parser.re2c.c"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy194;
	default:	goto yy48;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy196;
	default:	goto yy48;
	}
yy178:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy179;
	}
yy179:
#line 107 "lua-parser.re2c"
	{ return TK_GOTO; }
#line 1813 "lua-parser.re2c.c"
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy197;
	default:	goto yy48;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy199;
	default:	goto yy48;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy200;
	default:	goto yy48;
	}
yy183:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy184;
	}
yy184:
#line 82 "lua-parser.re2c"
	{ return TK_THEN; }
#line 1903 "lua-parser.re2c.c"
yy185:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy186;
	}
yy186:
#line 83 "lua-parser.re2c"
	{ return TK_TRUE; }
#line 1975 "lua-parser.re2c.c"
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy201;
	default:	goto yy48;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy203;
	default:	goto yy48;
	}
yy189:
	++YYCURSOR;
#line 109 "lua-parser.re2c"
	{ return TK_LABEL; }
#line 1992 "lua-parser.re2c.c"
yy191:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy192;
	}
yy192:
#line 65 "lua-parser.re2c"
	{ return TK_BREAK; }
#line 2064 "lua-parser.re2c.c"
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy205;
	default:	goto yy48;
	}
yy194:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy195;
	}
yy195:
#line 70 "lua-parser.re2c"
	{ return TK_FALSE; }
#line 2142 "lua-parser.re2c.c"
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy207;
	default:	goto yy48;
	}
yy197:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy198;
	}
yy198:
#line 76 "lua-parser.re2c"
	{ return TK_LOCAL; }
#line 2220 "lua-parser.re2c.c"
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy208;
	default:	goto yy48;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy210;
	default:	goto yy48;
	}
yy201:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy202;
	}
yy202:
#line 84 "lua-parser.re2c"
	{ return TK_UNTIL; }
#line 2304 "lua-parser.re2c.c"
yy203:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy204;
	}
yy204:
#line 85 "lua-parser.re2c"
	{ return TK_WHILE; }
#line 2376 "lua-parser.re2c.c"
yy205:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy206;
	}
yy206:
#line 68 "lua-parser.re2c"
	{ return TK_ELSEIF; }
#line 2448 "lua-parser.re2c.c"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy212;
	default:	goto yy48;
	}
yy208:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy209;
	}
yy209:
#line 80 "lua-parser.re2c"
	{ return TK_REPEAT; }
#line 2526 "lua-parser.re2c.c"
yy210:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy211;
	}
yy211:
#line 81 "lua-parser.re2c"
	{ return TK_RETURN; }
#line 2598 "lua-parser.re2c.c"
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy213;
	default:	goto yy48;
	}
yy213:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy214;
	}
yy214:
#line 72 "lua-parser.re2c"
	{ return TK_FUNCTION; }
#line 2676 "lua-parser.re2c.c"
}
#line 152 "lua-parser.re2c"


LongString:


#line 2684 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy217;
	case '\n':	goto yy221;
	case '[':	goto yy223;
	case ']':	goto yy224;
	default:	goto yy219;
	}
yy217:
	++YYCURSOR;
#line 164 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long string"); exit(1);}
#line 2699 "lua-parser.re2c.c"
yy219:
	++YYCURSOR;
yy220:
#line 163 "lua-parser.re2c"
	{ goto LongString; }
#line 2705 "lua-parser.re2c.c"
yy221:
	++YYCURSOR;
#line 161 "lua-parser.re2c"
	{ processNewLine(s); goto LongString; }
#line 2710 "lua-parser.re2c.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case '[':	goto yy225;
	default:	goto yy220;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case ']':	goto yy227;
	default:	goto yy220;
	}
yy225:
	++YYCURSOR;
#line 158 "lua-parser.re2c"
	{ nest_count++; goto LongString; }
#line 2727 "lua-parser.re2c.c"
yy227:
	++YYCURSOR;
#line 159 "lua-parser.re2c"
	{ if( nest_count == 0 ) { return TK_LONGSTRING; }
                     nest_count--; goto LongString; }
#line 2733 "lua-parser.re2c.c"
}
#line 166 "lua-parser.re2c"


Comment:


#line 2741 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy232;
	case '\n':	goto yy231;
	default:	goto yy234;
	}
yy231:
#line 172 "lua-parser.re2c"
	{ return TK_COMMENT; }
#line 2753 "lua-parser.re2c.c"
yy232:
	++YYCURSOR;
#line 173 "lua-parser.re2c"
	{ goto regular; }
#line 2758 "lua-parser.re2c.c"
yy234:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy231;
	default:	goto yy234;
	}
}
#line 175 "lua-parser.re2c"


LongComment:


#line 2774 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy238;
	case '\n':	goto yy242;
	case '[':	goto yy244;
	case ']':	goto yy245;
	default:	goto yy240;
	}
yy238:
	++YYCURSOR;
#line 187 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long comment"); exit(1);}
#line 2789 "lua-parser.re2c.c"
yy240:
	++YYCURSOR;
yy241:
#line 186 "lua-parser.re2c"
	{ goto LongComment; }
#line 2795 "lua-parser.re2c.c"
yy242:
	++YYCURSOR;
#line 185 "lua-parser.re2c"
	{ processNewLine(s); goto LongComment; }
#line 2800 "lua-parser.re2c.c"
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case '[':	goto yy246;
	default:	goto yy241;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case ']':	goto yy248;
	default:	goto yy241;
	}
yy246:
	++YYCURSOR;
#line 181 "lua-parser.re2c"
	{ nest_count++; goto LongComment; }
#line 2817 "lua-parser.re2c.c"
yy248:
	++YYCURSOR;
#line 182 "lua-parser.re2c"
	{ if( nest_count == 0 ) return TK_LONGCOMMENT;
                        nest_count--; goto LongComment;}
#line 2823 "lua-parser.re2c.c"
}
#line 189 "lua-parser.re2c"


  fprintf(stderr, "impossible"); exit(1);/* die */
}

static LuaParserToken *pushToken(LuaParserState *pState, LuaScanner *scanner, int token_id) {
  LuaParserToken* token_value = malloc(sizeof(*token_value));
  token_value->token_id = token_id;
  if(scanner->last_top != scanner->top) {
    token_value->space_before_size = (int)(scanner->top - scanner->last_top);
    token_value->space_before_pos = (int)(scanner->last_top - pState->src);
  }
  else {
    token_value->space_before_size = 0;
    token_value->space_before_pos = 0;
  }
  scanner->last_top = scanner->cur;
  token_value->token_value_size = (int)(scanner->cur - scanner->top);
  token_value->token_value =  scanner->top;
  pushLuaParserToken(pState, token_value);
  return token_value;
}

int main(int argc, char *argv[]) {

  FILE *fp, *traceFile;
  long size;
  char *buff, *buff_end;
  size_t bytes;
  int token;
  LuaScanner scanner;
  LuaParserState parser_state;
  void *parser;
  //ParserCount pCount;

  /* Open input file */
  const char *fname = "test.lua";
  if(argc > 1) fname = argv[1];
  fp = fopen(fname, "r");
  if(fp == NULL) {
    fprintf(stderr, "Can't open test file\n");
    exit(-1);
  }

  /* Open trace file */
  traceFile = fopen("trace.out", "w");
  if(traceFile == NULL) {
    fprintf(stderr, "Can't open trace file\n");
    exit(-1);
  }

  /* Get file size */
  fseek(fp, 0, SEEK_END);
  size = ftell(fp);
  rewind(fp);

  /*We only manage sources smaller than INT_MAX size */
  if(size > INT_MAX) {
    printf("Error file size bigger than %d\n", INT_MAX);
    exit(1);
  }

  /* Allocate buffer and read */
  buff = (char*) malloc((size+1) * sizeof(char));
  bytes = fread(buff, 1, size, fp);
  if (bytes != size) {
    fprintf(stderr, "Error reading input file\n");
    exit(-1);
  }
  buff[size] = '\0';

  /* Initialize scanner */
  scanner.line = 1;
  scanner.top = scanner.last_top = buff;
  scanner.cur = buff;
  scanner.pos = buff;
  scanner.ptr = buff;
  scanner.limit = buff+size;

  /* Initialize parser state */
  initializeLuaParserState(&parser_state);
  parser_state.src = buff;

  /* Initialize the parser state structure */
  //pCount.numFunctionDefinitions = 0;
  //pCount.numVariableDeclarations = 0;

  /* Pointer to the end of the buffer */
  buff_end = (char*) (((char*)buff) + size);

  /* Create parser and set up tracing */
  parser = LuaParserAlloc(malloc);
#ifndef NDEBUG
  LuaParserTrace(traceFile, "parser >> ");
#endif

  //printf("%d:%d:%d:%d\n", TK_SPACE, TK_COMMENT, TK_LONGCOMMENT, TK_THEEND);
  while((token = scan(&scanner, buff_end))) {
    if(token != TK_THEEND) {
      LuaParserToken *token_value = pushToken(&parser_state, &scanner, token);

      if(token < TK_LEMON_LAST_TOKEN) {
        LuaParser(parser, token, token_value, &parser_state);
      }
      else //SpecialTokens
      {
        //size_t gap_length = scanner.cur - scanner.top;
        switch(token) {
          case TK_SPACE:
            //printf("=S=%.*s=S=\n", (int)gap_length, scanner.top);
          break;
          case TK_COMMENT:
            //printf("=C=%.*s=C=\n", (int)gap_length, scanner.top);
            newStrFmt(token_value, "//%.*s", token_value->token_value_size-2, token_value->token_value+2);
          break;
          case TK_LONGCOMMENT:
            //printf("=LC=%.*s=LC=\n", (int)gap_length, scanner.top);
            newStrFmt(token_value, "/*%.*s*/", token_value->token_value_size, token_value->token_value);
          break;
        }
      }
    }
    else {
      if(scanner.last_top < buff_end) pushToken(&parser_state, &scanner, TK_SPACE);
      // Execute Parse for the last time
      LuaParser(parser, 0, NULL, &parser_state);
      break;
    }
  }
  /* Print results of parsing */
  //printf("Number of function definitions: %d.\n", pCount.numFunctionDefinitions);
  //printf("Number of variable declarations: %d.\n", pCount.numVariableDeclarations);

  /* output the reconstruction */
  doOutput(&parser_state);

  /* Deallocate parser */
  LuaParserFree(parser, free);
  
  resetLuaParserState(&parser_state);

  /* Close files and deallocate */
  fclose(fp);
  fclose(traceFile);
  free(buff);
  return(0);
}
