/* Generated by re2c 3.1 on Thu Feb 20 11:41:36 2025 */
#line 1 "lua-parser.re2c"
typedef struct LuaScanner {
  char *top, *last_top, *cur, *ptr, *pos, *limit;
  int line;
#ifndef NDEBUG
  char parsePrompt[32];
#endif
} LuaScanner;

#define   YYCTYPE     unsigned char
#define   YYCURSOR    s->cur
#define   YYMARKER    s->ptr
#define   YYLIMIT    s->limit

static void processNewLine(LuaScanner* s)
{
  //printf("%d:%.25s\n", s->line, s->top);
  s->pos = s->cur;
  s->line++;
#ifndef NDEBUG
  snprintf(s->parsePrompt, sizeof(s->parsePrompt), "parser %d >>", s->line);
#endif
}

static int scan(LuaScanner* s, char *buff_end) {

  int nest_count = 0, quote_size = 0, long_start_line;
  char *long_top;

regular:
  if (s->cur >= buff_end) {
    return TK_THEEND;
  }
  s->top = s->cur;

#line 78 "lua-parser.re2c"



#line 42 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy5;
		case '"': goto yy6;
		case '#': goto yy7;
		case '%': goto yy9;
		case '&': goto yy10;
		case '\'': goto yy11;
		case '(': goto yy12;
		case ')': goto yy13;
		case '*': goto yy14;
		case '+': goto yy15;
		case ',': goto yy16;
		case '-': goto yy17;
		case '.': goto yy19;
		case '/': goto yy21;
		case '0': goto yy23;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case ':': goto yy27;
		case ';': goto yy29;
		case '<': goto yy30;
		case '=': goto yy32;
		case '>': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'c':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'p':
		case 'q':
		case 's':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		case '[': goto yy39;
		case ']': goto yy41;
		case '^': goto yy42;
		case 'a': goto yy43;
		case 'b': goto yy44;
		case 'd': goto yy45;
		case 'e': goto yy46;
		case 'f': goto yy47;
		case 'g': goto yy48;
		case 'i': goto yy49;
		case 'l': goto yy50;
		case 'n': goto yy51;
		case 'o': goto yy52;
		case 'r': goto yy53;
		case 't': goto yy54;
		case 'u': goto yy55;
		case 'w': goto yy56;
		case '{': goto yy57;
		case '|': goto yy58;
		case '}': goto yy59;
		case '~': goto yy60;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 180 "lua-parser.re2c"
	{ goto regular; }
#line 149 "lua-parser.re2c.c"
yy2:
	++YYCURSOR;
yy3:
#line 174 "lua-parser.re2c"
	{ fprintf(stderr, "unexpected character: '%c' at line %d:%d\n",
                        *s->cur, s->line, (int)(s->cur - s->pos));
                        exit(1);
                    }
#line 158 "lua-parser.re2c.c"
yy4:
	++YYCURSOR;
#line 84 "lua-parser.re2c"
	{ goto regular; }
#line 163 "lua-parser.re2c.c"
yy5:
	++YYCURSOR;
#line 83 "lua-parser.re2c"
	{ processNewLine(s); goto regular; }
#line 168 "lua-parser.re2c.c"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy3;
	goto yy63;
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '!': goto yy67;
		default: goto yy8;
	}
yy8:
#line 122 "lua-parser.re2c"
	{ return TK_LEN; }
#line 183 "lua-parser.re2c.c"
yy9:
	++YYCURSOR;
#line 120 "lua-parser.re2c"
	{ return TK_MOD; }
#line 188 "lua-parser.re2c.c"
yy10:
	++YYCURSOR;
#line 141 "lua-parser.re2c"
	{ return TK_BITAND; }
#line 193 "lua-parser.re2c.c"
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy3;
	goto yy70;
yy12:
	++YYCURSOR;
#line 150 "lua-parser.re2c"
	{ return TK_LPAREN; }
#line 203 "lua-parser.re2c.c"
yy13:
	++YYCURSOR;
#line 151 "lua-parser.re2c"
	{ return TK_RPAREN; }
#line 208 "lua-parser.re2c.c"
yy14:
	++YYCURSOR;
#line 119 "lua-parser.re2c"
	{ return TK_MUL; }
#line 213 "lua-parser.re2c.c"
yy15:
	++YYCURSOR;
#line 116 "lua-parser.re2c"
	{ return TK_PLUS; }
#line 218 "lua-parser.re2c.c"
yy16:
	++YYCURSOR;
#line 146 "lua-parser.re2c"
	{ return TK_COMMA; }
#line 223 "lua-parser.re2c.c"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy73;
		default: goto yy18;
	}
yy18:
#line 117 "lua-parser.re2c"
	{ return TK_MINUS; }
#line 233 "lua-parser.re2c.c"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy75;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy77;
		default: goto yy20;
	}
yy20:
#line 149 "lua-parser.re2c"
	{ return TK_DOT; }
#line 253 "lua-parser.re2c.c"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '/': goto yy79;
		default: goto yy22;
	}
yy22:
#line 118 "lua-parser.re2c"
	{ return TK_DIV; }
#line 263 "lua-parser.re2c.c"
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'X':
		case 'x': goto yy84;
		default: goto yy26;
	}
yy24:
#line 163 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 275 "lua-parser.re2c.c"
yy25:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
yy26:
	switch (yych) {
		case '.': goto yy80;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case 'E':
		case 'e': goto yy81;
		case 'L': goto yy82;
		case 'U': goto yy83;
		case 'l': goto yy85;
		case 'u': goto yy86;
		default: goto yy24;
	}
yy27:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ':': goto yy87;
		default: goto yy28;
	}
yy28:
#line 148 "lua-parser.re2c"
	{ return TK_COLON; }
#line 310 "lua-parser.re2c.c"
yy29:
	++YYCURSOR;
#line 147 "lua-parser.re2c"
	{ return TK_SEMICOLON; }
#line 315 "lua-parser.re2c.c"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case '<': goto yy88;
		case '=': goto yy89;
		default: goto yy31;
	}
yy31:
#line 125 "lua-parser.re2c"
	{ return TK_LT; }
#line 326 "lua-parser.re2c.c"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy90;
		default: goto yy33;
	}
yy33:
#line 115 "lua-parser.re2c"
	{ return TK_ASSIGN; }
#line 336 "lua-parser.re2c.c"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy91;
		case '>': goto yy92;
		default: goto yy35;
	}
yy35:
#line 126 "lua-parser.re2c"
	{ return TK_BT; }
#line 347 "lua-parser.re2c.c"
yy36:
	yych = *++YYCURSOR;
yy37:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy38;
	}
yy38:
#line 159 "lua-parser.re2c"
	{ return TK_NAME; }
#line 420 "lua-parser.re2c.c"
yy39:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '=': goto yy93;
		case '[': goto yy94;
		default: goto yy40;
	}
yy40:
#line 154 "lua-parser.re2c"
	{ return TK_LBRACKET; }
#line 432 "lua-parser.re2c.c"
yy41:
	++YYCURSOR;
#line 155 "lua-parser.re2c"
	{ return TK_RBRACKET; }
#line 437 "lua-parser.re2c.c"
yy42:
	++YYCURSOR;
#line 121 "lua-parser.re2c"
	{ return TK_POW; }
#line 442 "lua-parser.re2c.c"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy95;
		default: goto yy37;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy96;
		default: goto yy37;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy97;
		default: goto yy37;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy99;
		case 'n': goto yy100;
		default: goto yy37;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy101;
		case 'o': goto yy102;
		case 'u': goto yy103;
		default: goto yy37;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy104;
		default: goto yy37;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy105;
		case 'n': goto yy107;
		default: goto yy37;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy109;
		default: goto yy37;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy110;
		case 'o': goto yy111;
		default: goto yy37;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy112;
		default: goto yy37;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy114;
		default: goto yy37;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy115;
		case 'r': goto yy116;
		default: goto yy37;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy117;
		default: goto yy37;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy118;
		default: goto yy37;
	}
yy57:
	++YYCURSOR;
#line 152 "lua-parser.re2c"
	{ return TK_LBRACE; }
#line 537 "lua-parser.re2c.c"
yy58:
	++YYCURSOR;
#line 140 "lua-parser.re2c"
	{ return TK_BITOR; }
#line 542 "lua-parser.re2c.c"
yy59:
	++YYCURSOR;
#line 153 "lua-parser.re2c"
	{ return TK_RBRACE; }
#line 547 "lua-parser.re2c.c"
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy119;
		default: goto yy61;
	}
yy61:
#line 139 "lua-parser.re2c"
	{ return TK_BITNOT; }
#line 557 "lua-parser.re2c.c"
yy62:
	yych = *++YYCURSOR;
yy63:
	switch (yych) {
		case 0x00: goto yy64;
		case '"': goto yy65;
		case '\\': goto yy66;
		default: goto yy62;
	}
yy64:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy24;
		case 2: goto yy28;
		case 3: goto yy40;
		case 4: goto yy74;
		case 5: goto yy78;
		default: goto yy129;
	}
yy65:
	++YYCURSOR;
#line 167 "lua-parser.re2c"
	{ return TK_STRING; }
#line 582 "lua-parser.re2c.c"
yy66:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy64;
	goto yy62;
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00:
		case '\n': goto yy68;
		default: goto yy67;
	}
yy68:
#line 170 "lua-parser.re2c"
	{ goto regular; }
#line 597 "lua-parser.re2c.c"
yy69:
	yych = *++YYCURSOR;
yy70:
	switch (yych) {
		case 0x00: goto yy64;
		case '\'': goto yy71;
		case '\\': goto yy72;
		default: goto yy69;
	}
yy71:
	++YYCURSOR;
#line 166 "lua-parser.re2c"
	{ return TK_STRING; }
#line 611 "lua-parser.re2c.c"
yy72:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy64;
	goto yy69;
yy73:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '[': goto yy120;
		default: goto yy74;
	}
yy74:
#line 88 "lua-parser.re2c"
	{ goto Comment; }
#line 626 "lua-parser.re2c.c"
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy121;
		default: goto yy76;
	}
yy76:
#line 124 "lua-parser.re2c"
	{ return TK_CONCAT; }
#line 636 "lua-parser.re2c.c"
yy77:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy77;
		case 'E':
		case 'e': goto yy81;
		default: goto yy78;
	}
yy78:
#line 162 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 658 "lua-parser.re2c.c"
yy79:
	++YYCURSOR;
#line 135 "lua-parser.re2c"
	{ return TK_IDIV; }
#line 663 "lua-parser.re2c.c"
yy80:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'i': goto yy78;
		default: goto yy123;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy124;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy125;
		default: goto yy64;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy126;
		default: goto yy64;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy82;
		default: goto yy64;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy127;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy128;
		default: goto yy64;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy126;
		default: goto yy64;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy85;
		default: goto yy64;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':': goto yy64;
		default: goto yy131;
	}
yy88:
	++YYCURSOR;
#line 142 "lua-parser.re2c"
	{ return TK_SHL; }
#line 760 "lua-parser.re2c.c"
yy89:
	++YYCURSOR;
#line 130 "lua-parser.re2c"
	{ return TK_LTEQ; }
#line 765 "lua-parser.re2c.c"
yy90:
	++YYCURSOR;
#line 128 "lua-parser.re2c"
	{ return TK_EQ; }
#line 770 "lua-parser.re2c.c"
yy91:
	++YYCURSOR;
#line 129 "lua-parser.re2c"
	{ return TK_BTEQ; }
#line 775 "lua-parser.re2c.c"
yy92:
	++YYCURSOR;
#line 143 "lua-parser.re2c"
	{ return TK_SHR; }
#line 780 "lua-parser.re2c.c"
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy93;
		case '[': goto yy94;
		default: goto yy64;
	}
yy94:
	++YYCURSOR;
#line 156 "lua-parser.re2c"
	{ long_start_line = s->line; nest_count=0; quote_size = (int)(s->cur - s->top); goto LongString; }
#line 792 "lua-parser.re2c.c"
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy132;
		default: goto yy37;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy134;
		default: goto yy37;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy98;
	}
yy98:
#line 93 "lua-parser.re2c"
	{ return TK_DO; }
#line 876 "lua-parser.re2c.c"
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy135;
		default: goto yy37;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy136;
		default: goto yy37;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy138;
		default: goto yy37;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy139;
		default: goto yy37;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy141;
		default: goto yy37;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy142;
		default: goto yy37;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy106;
	}
yy106:
#line 101 "lua-parser.re2c"
	{ return TK_IF; }
#line 984 "lua-parser.re2c.c"
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy108;
	}
yy108:
#line 102 "lua-parser.re2c"
	{ return TK_IN; }
#line 1056 "lua-parser.re2c.c"
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy143;
		default: goto yy37;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy144;
		default: goto yy37;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy146;
		default: goto yy37;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy113;
	}
yy113:
#line 106 "lua-parser.re2c"
	{ return TK_OR; }
#line 1146 "lua-parser.re2c.c"
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy148;
		case 't': goto yy149;
		default: goto yy37;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy150;
		default: goto yy37;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy151;
		default: goto yy37;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy152;
		default: goto yy37;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy153;
		default: goto yy37;
	}
yy119:
	++YYCURSOR;
#line 131 "lua-parser.re2c"
	{ return TK_NEQ; }
#line 1182 "lua-parser.re2c.c"
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy120;
		case '[': goto yy154;
		default: goto yy64;
	}
yy121:
	++YYCURSOR;
#line 123 "lua-parser.re2c"
	{ return TK_ELLIPSIS; }
#line 1194 "lua-parser.re2c.c"
yy122:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
yy123:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy122;
		case 'E':
		case 'e': goto yy81;
		case 'i': goto yy155;
		default: goto yy78;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy125;
		default: goto yy64;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy125;
		default: goto yy78;
	}
yy126:
	++YYCURSOR;
	goto yy24;
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy156;
		default: goto yy64;
	}
yy128:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy156;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy128;
		case 'E':
		case 'e': goto yy157;
		case 'L': goto yy158;
		case 'P':
		case 'p': goto yy159;
		case 'U': goto yy160;
		case 'l': goto yy161;
		case 'u': goto yy162;
		default: goto yy129;
	}
yy129:
#line 164 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 1313 "lua-parser.re2c.c"
yy130:
	yych = *++YYCURSOR;
yy131:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy130;
		case ':': goto yy163;
		default: goto yy64;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy133;
	}
yy133:
#line 91 "lua-parser.re2c"
	{ return TK_AND; }
#line 1455 "lua-parser.re2c.c"
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy164;
		default: goto yy37;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy165;
		default: goto yy37;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy137;
	}
yy137:
#line 96 "lua-parser.re2c"
	{ return TK_END; }
#line 1539 "lua-parser.re2c.c"
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy167;
		default: goto yy37;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy140;
	}
yy140:
#line 98 "lua-parser.re2c"
	{ return TK_FOR; }
#line 1617 "lua-parser.re2c.c"
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy168;
		default: goto yy37;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy169;
		default: goto yy37;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy171;
		default: goto yy37;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy145;
	}
yy145:
#line 104 "lua-parser.re2c"
	{ return TK_NIL; }
#line 1707 "lua-parser.re2c.c"
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy147;
	}
yy147:
#line 105 "lua-parser.re2c"
	{ return TK_NOT; }
#line 1779 "lua-parser.re2c.c"
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy172;
		default: goto yy37;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy173;
		default: goto yy37;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy174;
		default: goto yy37;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy176;
		default: goto yy37;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy178;
		default: goto yy37;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy179;
		default: goto yy37;
	}
yy154:
	++YYCURSOR;
#line 87 "lua-parser.re2c"
	{ long_start_line = s->line; nest_count=0; quote_size = ((int)(s->cur - s->top)) - 2;  goto LongComment; }
#line 1820 "lua-parser.re2c.c"
yy155:
	++YYCURSOR;
#line 165 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 1825 "lua-parser.re2c.c"
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy156;
		case 'E':
		case 'e': goto yy180;
		default: goto yy78;
	}
yy157:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '+':
		case '-': goto yy124;
		case '.': goto yy156;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy181;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy128;
		case 'E':
		case 'e': goto yy157;
		case 'L': goto yy158;
		case 'P':
		case 'p': goto yy159;
		case 'U': goto yy160;
		case 'l': goto yy161;
		case 'u': goto yy162;
		default: goto yy129;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy182;
		default: goto yy64;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy183;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy184;
		default: goto yy64;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy158;
		default: goto yy64;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy182;
		default: goto yy64;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy161;
		default: goto yy64;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy185;
		default: goto yy64;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy186;
		default: goto yy37;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		case 'i': goto yy188;
		default: goto yy166;
	}
yy166:
#line 94 "lua-parser.re2c"
	{ return TK_ELSE; }
#line 2014 "lua-parser.re2c.c"
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy189;
		default: goto yy37;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy191;
		default: goto yy37;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy170;
	}
yy170:
#line 134 "lua-parser.re2c"
	{ return TK_GOTO; }
#line 2098 "lua-parser.re2c.c"
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy192;
		default: goto yy37;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy194;
		default: goto yy37;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy195;
		default: goto yy37;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy175;
	}
yy175:
#line 109 "lua-parser.re2c"
	{ return TK_THEN; }
#line 2188 "lua-parser.re2c.c"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy177;
	}
yy177:
#line 110 "lua-parser.re2c"
	{ return TK_TRUE; }
#line 2260 "lua-parser.re2c.c"
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy196;
		default: goto yy37;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy198;
		default: goto yy37;
	}
yy180:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '+':
		case '-': goto yy124;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy156;
		case 'E':
		case 'e': goto yy180;
		default: goto yy78;
	}
yy181:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy156;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy181;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy128;
		case 'E':
		case 'e': goto yy157;
		case 'L': goto yy158;
		case 'P':
		case 'p': goto yy159;
		case 'U': goto yy160;
		case 'l': goto yy161;
		case 'u': goto yy162;
		default: goto yy78;
	}
yy182:
	++YYCURSOR;
	goto yy129;
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy184;
		default: goto yy64;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy184;
		default: goto yy129;
	}
yy185:
	++YYCURSOR;
#line 136 "lua-parser.re2c"
	{ return TK_LABEL; }
#line 2375 "lua-parser.re2c.c"
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy187;
	}
yy187:
#line 92 "lua-parser.re2c"
	{ return TK_BREAK; }
#line 2447 "lua-parser.re2c.c"
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy200;
		default: goto yy37;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy190;
	}
yy190:
#line 97 "lua-parser.re2c"
	{ return TK_FALSE; }
#line 2525 "lua-parser.re2c.c"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy202;
		default: goto yy37;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy193;
	}
yy193:
#line 103 "lua-parser.re2c"
	{ return TK_LOCAL; }
#line 2603 "lua-parser.re2c.c"
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy203;
		default: goto yy37;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy205;
		default: goto yy37;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy197;
	}
yy197:
#line 111 "lua-parser.re2c"
	{ return TK_UNTIL; }
#line 2687 "lua-parser.re2c.c"
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy199;
	}
yy199:
#line 112 "lua-parser.re2c"
	{ return TK_WHILE; }
#line 2759 "lua-parser.re2c.c"
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy201;
	}
yy201:
#line 95 "lua-parser.re2c"
	{ return TK_ELSEIF; }
#line 2831 "lua-parser.re2c.c"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy207;
		default: goto yy37;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy204;
	}
yy204:
#line 107 "lua-parser.re2c"
	{ return TK_REPEAT; }
#line 2909 "lua-parser.re2c.c"
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy206;
	}
yy206:
#line 108 "lua-parser.re2c"
	{ return TK_RETURN; }
#line 2981 "lua-parser.re2c.c"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy208;
		default: goto yy37;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy36;
		default: goto yy209;
	}
yy209:
#line 99 "lua-parser.re2c"
	{ return TK_FUNCTION; }
#line 3059 "lua-parser.re2c.c"
}
#line 182 "lua-parser.re2c"


LongString:
  long_top = s->cur;


#line 3068 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy211;
		case '\n': goto yy214;
		case '[': goto yy215;
		case ']': goto yy216;
		default: goto yy212;
	}
yy211:
	++YYCURSOR;
#line 196 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long string at line %d\n", long_start_line); exit(1);}
#line 3083 "lua-parser.re2c.c"
yy212:
	++YYCURSOR;
yy213:
#line 195 "lua-parser.re2c"
	{ goto LongString; }
#line 3089 "lua-parser.re2c.c"
yy214:
	++YYCURSOR;
#line 193 "lua-parser.re2c"
	{ processNewLine(s); goto LongString; }
#line 3094 "lua-parser.re2c.c"
yy215:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '=': goto yy217;
		case '[': goto yy219;
		default: goto yy213;
	}
yy216:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '=': goto yy220;
		case ']': goto yy221;
		default: goto yy213;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy217;
		case '[': goto yy219;
		default: goto yy218;
	}
yy218:
	YYCURSOR = YYMARKER;
	goto yy213;
yy219:
	++YYCURSOR;
#line 189 "lua-parser.re2c"
	{ int qsz = (int)(s->cur - long_top); if(qsz == quote_size) nest_count++; goto LongString; }
#line 3123 "lua-parser.re2c.c"
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy220;
		case ']': goto yy221;
		default: goto yy218;
	}
yy221:
	++YYCURSOR;
	YYCURSOR -= 1;
#line 190 "lua-parser.re2c"
	{ int qsz = (int)(s->cur+1 - long_top); if( (nest_count == 0) && (qsz == quote_size)) { if(*s->cur == '\n') processNewLine(s); ++s->cur; return TK_LONGSTRING; };
                          if(qsz == quote_size) nest_count--; goto LongString; }
#line 3137 "lua-parser.re2c.c"
}
#line 198 "lua-parser.re2c"


Comment:


#line 3145 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy224;
		case '\n': goto yy223;
		default: goto yy225;
	}
yy223:
#line 204 "lua-parser.re2c"
	{ return TK_COMMENT; }
#line 3157 "lua-parser.re2c.c"
yy224:
	++YYCURSOR;
#line 205 "lua-parser.re2c"
	{ goto regular; }
#line 3162 "lua-parser.re2c.c"
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00:
		case '\n': goto yy223;
		default: goto yy225;
	}
}
#line 207 "lua-parser.re2c"


LongComment:
  long_top = s->cur;


#line 3178 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy227;
		case '\n': goto yy230;
		case '[': goto yy231;
		case ']': goto yy232;
		default: goto yy228;
	}
yy227:
	++YYCURSOR;
#line 220 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long comment at line %d\n", long_start_line); exit(1);}
#line 3193 "lua-parser.re2c.c"
yy228:
	++YYCURSOR;
yy229:
#line 219 "lua-parser.re2c"
	{ goto LongComment; }
#line 3199 "lua-parser.re2c.c"
yy230:
	++YYCURSOR;
#line 218 "lua-parser.re2c"
	{ processNewLine(s); goto LongComment; }
#line 3204 "lua-parser.re2c.c"
yy231:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '=': goto yy233;
		case '[': goto yy235;
		default: goto yy229;
	}
yy232:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '=': goto yy236;
		case ']': goto yy237;
		default: goto yy229;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy233;
		case '[': goto yy235;
		default: goto yy234;
	}
yy234:
	YYCURSOR = YYMARKER;
	goto yy229;
yy235:
	++YYCURSOR;
#line 214 "lua-parser.re2c"
	{ int qsz = (int)(s->cur - long_top); if(qsz == quote_size) nest_count++; goto LongComment; }
#line 3233 "lua-parser.re2c.c"
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy236;
		case ']': goto yy237;
		default: goto yy234;
	}
yy237:
	++YYCURSOR;
	YYCURSOR -= 1;
#line 215 "lua-parser.re2c"
	{ int qsz = (int)(s->cur+1 - long_top); if( (nest_count == 0) && (qsz == quote_size)) { if(*s->cur == '\n') processNewLine(s); ++s->cur; return TK_LONGCOMMENT; };
                          if(qsz == quote_size) nest_count--; goto LongComment; }
#line 3247 "lua-parser.re2c.c"
}
#line 222 "lua-parser.re2c"


  fprintf(stderr, "impossible"); exit(1);/* die */
}

static LuaParserToken *pushToken(LuaParserState *pState, LuaScanner *scanner, int token_id) {
  LuaParserToken* token_value = malloc(sizeof(*token_value));
  token_value->flags = 0;
  token_value->token_id = token_id;
  if(scanner->last_top != scanner->top) {
    token_value->space_before_size = (int)(scanner->top - scanner->last_top);
    token_value->space_before_pos = (int)(scanner->last_top - pState->src);
  }
  else {
    token_value->space_before_size = 0;
    token_value->space_before_pos = 0;
  }
  scanner->last_top = scanner->cur;
  token_value->token_value_size = (int)(scanner->cur - scanner->top);
  token_value->token_value =  scanner->top;
  pushLuaParserToken(pState, token_value);
  return token_value;
}

int main(int argc, char *argv[]) {

  FILE *fp, *traceFile;
  long size;
  char *buff, *buff_end;
  size_t bytes;
  int token;
  LuaScanner scanner;
  LuaParserState parser_state;
  void *parser;
  //ParserCount pCount;

  int fn_argc = 1;
  int noToCompound = 0;
  int withTrace = 0;
  if(argc > 2) {
    for(; fn_argc < (argc-1); ++fn_argc) {
      if (strcmp(argv[fn_argc] , "-nc") == 0) noToCompound = 1;
#ifndef NDEBUG
      else if (strcmp(argv[fn_argc] , "-t") == 0) withTrace = 1;
#endif
      else {
        printf("usage : %s [options] lua_fname\n\toptions:\n\t\t-nc\tdo not convert to compound assginments\n"
#ifndef NDEBUG
                 "\t\t-t\tgenerate parser trace\n"
#endif
	    , argv[0]);
        exit(1);
    }
   }
  }

  /* Open input file */
  const char *fname = "test.lua";
  if(argc > 1) fname = argv[fn_argc];
  fp = fopen(fname, "r");
  if(fp == NULL) {
    fprintf(stderr, "Can't open test file\n");
    exit(-1);
  }

  if(withTrace) {
	/* Open trace file */
	traceFile = fopen("trace.out", "w");
	if(traceFile == NULL) {
	    fprintf(stderr, "Can't open trace file\n");
	    exit(-1);
	}
  }

  /* Get file size */
  fseek(fp, 0, SEEK_END);
  size = ftell(fp);
  rewind(fp);

  /*We only manage sources smaller than INT_MAX size */
  if(size > INT_MAX) {
    printf("Error file size bigger than %d\n", INT_MAX);
    exit(1);
  }

  /*
  * Allocate buffer and read, +2 just in case file do not end in '\n'
  */
  buff = (char*) malloc((size+2) * sizeof(char));
  bytes = fread(buff, 1, size, fp);
  if (bytes != size) {
    fprintf(stderr, "Error reading input file\n");
    exit(-1);
  }
  buff[size] = '\0';

  if(size > 1 && buff[size-1] != '\n') {
    /* to make things easy to parse we need a '\n' at the end */
    buff[size] = '\n';
    buff[size+1] = '\0';
    ++size;
  }

  /* Initialize scanner */
  scanner.line = 1;
  scanner.top = scanner.last_top = buff;
  scanner.cur = buff;
  scanner.pos = buff;
  scanner.ptr = buff;
  scanner.limit = buff+size;
#ifndef NDEBUG
   snprintf(scanner.parsePrompt, sizeof(scanner.parsePrompt), "parser %d >>", scanner.line);
#endif

  /* Initialize parser state */
  initializeLuaParserState(&parser_state);
  parser_state.src = buff;
  parser_state.noToCompound = noToCompound;

  /* Initialize the parser state structure */
  //pCount.numFunctionDefinitions = 0;
  //pCount.numVariableDeclarations = 0;

  /* Pointer to the end of the buffer */
  buff_end = (char*) (((char*)buff) + size);

  /* Create parser and set up tracing */
  parser = LuaParserAlloc(malloc);
#ifndef NDEBUG
  if(withTrace) LuaParserTrace(traceFile, scanner.parsePrompt);
#endif

  //printf("%d:%d:%d:%d\n", TK_SPACE, TK_COMMENT, TK_LONGCOMMENT, TK_THEEND);
  while((token = scan(&scanner, buff_end))) {
    if(token != TK_THEEND) {
      LuaParserToken *token_value = pushToken(&parser_state, &scanner, token);
      //printf("\n==++== %d : %d : %.8s ::%.*s\n", scanner.line, token, scanner.top, token_value->token_value_size, token_value->token_value);

      if(token < TK_LEMON_LAST_TOKEN) {
        LuaParser(parser, token, token_value, &parser_state);
      }
      else //SpecialTokens
      {
        //size_t gap_length = scanner.cur - scanner.top;
        switch(token) {
          case TK_SPACE:
            //printf("=S=%.*s=S=\n", (int)gap_length, scanner.top);
          break;
          case TK_COMMENT:
            //printf("=C=%.*s=C=\n", (int)gap_length, scanner.top);
            newStrFmt(token_value, "//%.*s", token_value->token_value_size-2, token_value->token_value+2);
          break;
          case TK_LONGCOMMENT: {
            //printf("=LC=%.*s=LC=\n", (int)gap_length, scanner.top);
            int quote_end = 4; // "--[["
            while(token_value->token_value[quote_end-1] != '[') ++quote_end; //try to find the end
            newStrFmt(token_value, "/*%.*s*/", token_value->token_value_size - quote_end - (quote_end-2), // -2 for "--"
                                                                  token_value->token_value + quote_end);
          }
          break;
        }
      }
    }
    else {
      if(scanner.last_top < buff_end) pushToken(&parser_state, &scanner, TK_SPACE);
      // Execute Parse for the last time
      LuaParser(parser, 0, NULL, &parser_state);
      break;
    }
  }
  /* Print results of parsing */
  //printf("Number of function definitions: %d.\n", pCount.numFunctionDefinitions);
  //printf("Number of variable declarations: %d.\n", pCount.numVariableDeclarations);

  /* output the reconstruction */
  doOutput(&parser_state);

  /* Deallocate parser */
  LuaParserFree(parser, free);

  resetLuaParserState(&parser_state);

  /* Close files and deallocate */
  fclose(fp);
 if(withTrace)  fclose(traceFile);
  free(buff);
  return(0);
}
