/* Generated by re2c 1.1.1 on Mon Nov 26 17:03:54 2018 */
#line 1 "lua-parser.re2c"
typedef struct LuaScanner {
  char *top, *last_top, *cur, *ptr, *pos, *limit;
  int line;
} LuaScanner;

#define   YYCTYPE     unsigned char
#define   YYCURSOR    s->cur
#define   YYMARKER    s->ptr
#define   YYLIMIT    s->limit

static void processNewLine(LuaScanner* s)
{
  //printf("%d:%.25s\n", s->line, s->top);
  s->pos = s->cur;
  s->line++;
}

static int scan(LuaScanner* s, char *buff_end) {

  int nest_count = 0, quote_size = 0, long_start_line;
  char *long_top;

regular:
  if (s->cur >= buff_end) {
    return TK_THEEND;
  }
  s->top = s->cur;

#line 52 "lua-parser.re2c"



#line 36 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '"':	goto yy10;
	case '#':	goto yy11;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '\'':	goto yy17;
	case '(':	goto yy18;
	case ')':	goto yy20;
	case '*':	goto yy22;
	case '+':	goto yy24;
	case ',':	goto yy26;
	case '-':	goto yy28;
	case '.':	goto yy30;
	case '/':	goto yy32;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case ':':	goto yy37;
	case ';':	goto yy39;
	case '<':	goto yy41;
	case '=':	goto yy43;
	case '>':	goto yy45;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'c':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'p':
	case 'q':
	case 's':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	case '[':	goto yy50;
	case ']':	goto yy52;
	case '^':	goto yy54;
	case 'a':	goto yy56;
	case 'b':	goto yy57;
	case 'd':	goto yy58;
	case 'e':	goto yy59;
	case 'f':	goto yy60;
	case 'g':	goto yy61;
	case 'i':	goto yy62;
	case 'l':	goto yy63;
	case 'n':	goto yy64;
	case 'o':	goto yy65;
	case 'r':	goto yy66;
	case 't':	goto yy67;
	case 'u':	goto yy68;
	case 'w':	goto yy69;
	case '{':	goto yy70;
	case '|':	goto yy72;
	case '}':	goto yy74;
	case '~':	goto yy76;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 151 "lua-parser.re2c"
	{ goto regular; }
#line 143 "lua-parser.re2c.c"
yy4:
	++YYCURSOR;
yy5:
#line 145 "lua-parser.re2c"
	{ fprintf(stderr, "unexpected character: '%c' at line %d:%d\n",
                        *s->cur, s->line, (int)(s->cur - s->pos));
                        exit(1);
                    }
#line 152 "lua-parser.re2c.c"
yy6:
	++YYCURSOR;
#line 58 "lua-parser.re2c"
	{ goto regular; }
#line 157 "lua-parser.re2c.c"
yy8:
	++YYCURSOR;
#line 57 "lua-parser.re2c"
	{ processNewLine(s); goto regular; }
#line 162 "lua-parser.re2c.c"
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy79;
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case '!':	goto yy84;
	default:	goto yy12;
	}
yy12:
#line 96 "lua-parser.re2c"
	{ return TK_LEN; }
#line 177 "lua-parser.re2c.c"
yy13:
	++YYCURSOR;
#line 94 "lua-parser.re2c"
	{ return TK_MOD; }
#line 182 "lua-parser.re2c.c"
yy15:
	++YYCURSOR;
#line 115 "lua-parser.re2c"
	{ return TK_BITAND; }
#line 187 "lua-parser.re2c.c"
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy88;
yy18:
	++YYCURSOR;
#line 124 "lua-parser.re2c"
	{ return TK_LPAREN; }
#line 197 "lua-parser.re2c.c"
yy20:
	++YYCURSOR;
#line 125 "lua-parser.re2c"
	{ return TK_RPAREN; }
#line 202 "lua-parser.re2c.c"
yy22:
	++YYCURSOR;
#line 93 "lua-parser.re2c"
	{ return TK_MUL; }
#line 207 "lua-parser.re2c.c"
yy24:
	++YYCURSOR;
#line 90 "lua-parser.re2c"
	{ return TK_PLUS; }
#line 212 "lua-parser.re2c.c"
yy26:
	++YYCURSOR;
#line 101 "lua-parser.re2c"
	{ return TK_COMMA; }
#line 217 "lua-parser.re2c.c"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy92;
	default:	goto yy29;
	}
yy29:
#line 91 "lua-parser.re2c"
	{ return TK_MINUS; }
#line 227 "lua-parser.re2c.c"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy94;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	default:	goto yy31;
	}
yy31:
#line 123 "lua-parser.re2c"
	{ return TK_DOT; }
#line 247 "lua-parser.re2c.c"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case '/':	goto yy98;
	default:	goto yy33;
	}
yy33:
#line 92 "lua-parser.re2c"
	{ return TK_DIV; }
#line 257 "lua-parser.re2c.c"
yy34:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy96;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy36;
	}
yy36:
#line 136 "lua-parser.re2c"
	{ return TK_NUMBER; }
#line 280 "lua-parser.re2c.c"
yy37:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ':':	goto yy101;
	default:	goto yy38;
	}
yy38:
#line 122 "lua-parser.re2c"
	{ return TK_COLON; }
#line 291 "lua-parser.re2c.c"
yy39:
	++YYCURSOR;
#line 121 "lua-parser.re2c"
	{ return TK_SEMICOLON; }
#line 296 "lua-parser.re2c.c"
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case '<':	goto yy102;
	case '=':	goto yy104;
	default:	goto yy42;
	}
yy42:
#line 99 "lua-parser.re2c"
	{ return TK_LT; }
#line 307 "lua-parser.re2c.c"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy106;
	default:	goto yy44;
	}
yy44:
#line 89 "lua-parser.re2c"
	{ return TK_ASSIGN; }
#line 317 "lua-parser.re2c.c"
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy108;
	case '>':	goto yy110;
	default:	goto yy46;
	}
yy46:
#line 100 "lua-parser.re2c"
	{ return TK_BT; }
#line 328 "lua-parser.re2c.c"
yy47:
	yych = *++YYCURSOR;
yy48:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy49;
	}
yy49:
#line 133 "lua-parser.re2c"
	{ return TK_NAME; }
#line 401 "lua-parser.re2c.c"
yy50:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy112;
	case '[':	goto yy114;
	default:	goto yy51;
	}
yy51:
#line 128 "lua-parser.re2c"
	{ return TK_LBRACKET; }
#line 413 "lua-parser.re2c.c"
yy52:
	++YYCURSOR;
#line 129 "lua-parser.re2c"
	{ return TK_RBRACKET; }
#line 418 "lua-parser.re2c.c"
yy54:
	++YYCURSOR;
#line 95 "lua-parser.re2c"
	{ return TK_POW; }
#line 423 "lua-parser.re2c.c"
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy116;
	default:	goto yy48;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy117;
	default:	goto yy48;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy118;
	default:	goto yy48;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy120;
	case 'n':	goto yy121;
	default:	goto yy48;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy122;
	case 'o':	goto yy123;
	case 'u':	goto yy124;
	default:	goto yy48;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy125;
	default:	goto yy48;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy126;
	case 'n':	goto yy128;
	default:	goto yy48;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy130;
	default:	goto yy48;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy131;
	case 'o':	goto yy132;
	default:	goto yy48;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy133;
	default:	goto yy48;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy135;
	default:	goto yy48;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy136;
	case 'r':	goto yy137;
	default:	goto yy48;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy138;
	default:	goto yy48;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy139;
	default:	goto yy48;
	}
yy70:
	++YYCURSOR;
#line 126 "lua-parser.re2c"
	{ return TK_LBRACE; }
#line 518 "lua-parser.re2c.c"
yy72:
	++YYCURSOR;
#line 114 "lua-parser.re2c"
	{ return TK_BITOR; }
#line 523 "lua-parser.re2c.c"
yy74:
	++YYCURSOR;
#line 127 "lua-parser.re2c"
	{ return TK_RBRACE; }
#line 528 "lua-parser.re2c.c"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy140;
	default:	goto yy77;
	}
yy77:
#line 113 "lua-parser.re2c"
	{ return TK_BITNOT; }
#line 538 "lua-parser.re2c.c"
yy78:
	yych = *++YYCURSOR;
yy79:
	switch (yych) {
	case 0x00:	goto yy80;
	case '"':	goto yy81;
	case '\\':	goto yy83;
	default:	goto yy78;
	}
yy80:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy36;
	case 2: 	goto yy38;
	case 3: 	goto yy51;
	default:	goto yy93;
	}
yy81:
	++YYCURSOR;
#line 138 "lua-parser.re2c"
	{ return TK_STRING; }
#line 561 "lua-parser.re2c.c"
yy83:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy80;
	goto yy78;
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy86;
	default:	goto yy84;
	}
yy86:
#line 141 "lua-parser.re2c"
	{ goto regular; }
#line 576 "lua-parser.re2c.c"
yy87:
	yych = *++YYCURSOR;
yy88:
	switch (yych) {
	case 0x00:	goto yy80;
	case '\'':	goto yy89;
	case '\\':	goto yy91;
	default:	goto yy87;
	}
yy89:
	++YYCURSOR;
#line 137 "lua-parser.re2c"
	{ return TK_STRING; }
#line 590 "lua-parser.re2c.c"
yy91:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy80;
	goto yy87;
yy92:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '[':	goto yy142;
	default:	goto yy93;
	}
yy93:
#line 62 "lua-parser.re2c"
	{ goto Comment; }
#line 605 "lua-parser.re2c.c"
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy144;
	default:	goto yy95;
	}
yy95:
#line 98 "lua-parser.re2c"
	{ return TK_CONCAT; }
#line 615 "lua-parser.re2c.c"
yy96:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy36;
	}
yy98:
	++YYCURSOR;
#line 109 "lua-parser.re2c"
	{ return TK_IDIV; }
#line 638 "lua-parser.re2c.c"
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy146;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	default:	goto yy80;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':	goto yy80;
	default:	goto yy150;
	}
yy102:
	++YYCURSOR;
#line 116 "lua-parser.re2c"
	{ return TK_SHL; }
#line 676 "lua-parser.re2c.c"
yy104:
	++YYCURSOR;
#line 104 "lua-parser.re2c"
	{ return TK_LTEQ; }
#line 681 "lua-parser.re2c.c"
yy106:
	++YYCURSOR;
#line 102 "lua-parser.re2c"
	{ return TK_EQ; }
#line 686 "lua-parser.re2c.c"
yy108:
	++YYCURSOR;
#line 103 "lua-parser.re2c"
	{ return TK_BTEQ; }
#line 691 "lua-parser.re2c.c"
yy110:
	++YYCURSOR;
#line 117 "lua-parser.re2c"
	{ return TK_SHR; }
#line 696 "lua-parser.re2c.c"
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy112;
	case '[':	goto yy114;
	default:	goto yy80;
	}
yy114:
	++YYCURSOR;
#line 130 "lua-parser.re2c"
	{ long_start_line = s->line; nest_count=0; quote_size = (int)(s->cur - s->top); goto LongString; }
#line 708 "lua-parser.re2c.c"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy151;
	default:	goto yy48;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy153;
	default:	goto yy48;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy119;
	}
yy119:
#line 67 "lua-parser.re2c"
	{ return TK_DO; }
#line 792 "lua-parser.re2c.c"
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy154;
	default:	goto yy48;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy155;
	default:	goto yy48;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy157;
	default:	goto yy48;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy158;
	default:	goto yy48;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy160;
	default:	goto yy48;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy161;
	default:	goto yy48;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy127;
	}
yy127:
#line 75 "lua-parser.re2c"
	{ return TK_IF; }
#line 900 "lua-parser.re2c.c"
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy129;
	}
yy129:
#line 76 "lua-parser.re2c"
	{ return TK_IN; }
#line 972 "lua-parser.re2c.c"
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy162;
	default:	goto yy48;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy163;
	default:	goto yy48;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy165;
	default:	goto yy48;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy134;
	}
yy134:
#line 80 "lua-parser.re2c"
	{ return TK_OR; }
#line 1062 "lua-parser.re2c.c"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy167;
	case 't':	goto yy168;
	default:	goto yy48;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy169;
	default:	goto yy48;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy170;
	default:	goto yy48;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy171;
	default:	goto yy48;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy172;
	default:	goto yy48;
	}
yy140:
	++YYCURSOR;
#line 105 "lua-parser.re2c"
	{ return TK_NEQ; }
#line 1098 "lua-parser.re2c.c"
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy142;
	case '[':	goto yy173;
	default:	goto yy80;
	}
yy144:
	++YYCURSOR;
#line 97 "lua-parser.re2c"
	{ return TK_ELLIPSIS; }
#line 1110 "lua-parser.re2c.c"
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	default:	goto yy80;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy147;
	default:	goto yy36;
	}
yy149:
	yych = *++YYCURSOR;
yy150:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy149;
	case ':':	goto yy175;
	default:	goto yy80;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy152;
	}
yy152:
#line 65 "lua-parser.re2c"
	{ return TK_AND; }
#line 1282 "lua-parser.re2c.c"
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy176;
	default:	goto yy48;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy177;
	default:	goto yy48;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy156;
	}
yy156:
#line 70 "lua-parser.re2c"
	{ return TK_END; }
#line 1366 "lua-parser.re2c.c"
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy179;
	default:	goto yy48;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy159;
	}
yy159:
#line 72 "lua-parser.re2c"
	{ return TK_FOR; }
#line 1444 "lua-parser.re2c.c"
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy180;
	default:	goto yy48;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy181;
	default:	goto yy48;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy183;
	default:	goto yy48;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy164;
	}
yy164:
#line 78 "lua-parser.re2c"
	{ return TK_NIL; }
#line 1534 "lua-parser.re2c.c"
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy166;
	}
yy166:
#line 79 "lua-parser.re2c"
	{ return TK_NOT; }
#line 1606 "lua-parser.re2c.c"
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy184;
	default:	goto yy48;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy185;
	default:	goto yy48;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy186;
	default:	goto yy48;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy48;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy190;
	default:	goto yy48;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy191;
	default:	goto yy48;
	}
yy173:
	++YYCURSOR;
#line 61 "lua-parser.re2c"
	{ long_start_line = s->line; nest_count=0; quote_size = ((int)(s->cur - s->top)) - 2;  goto LongComment; }
#line 1647 "lua-parser.re2c.c"
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy192;
	default:	goto yy80;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy194;
	default:	goto yy48;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	case 'i':	goto yy196;
	default:	goto yy178;
	}
yy178:
#line 68 "lua-parser.re2c"
	{ return TK_ELSE; }
#line 1731 "lua-parser.re2c.c"
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy197;
	default:	goto yy48;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy199;
	default:	goto yy48;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy182;
	}
yy182:
#line 108 "lua-parser.re2c"
	{ return TK_GOTO; }
#line 1815 "lua-parser.re2c.c"
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy200;
	default:	goto yy48;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy202;
	default:	goto yy48;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy203;
	default:	goto yy48;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy187;
	}
yy187:
#line 83 "lua-parser.re2c"
	{ return TK_THEN; }
#line 1905 "lua-parser.re2c.c"
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy189;
	}
yy189:
#line 84 "lua-parser.re2c"
	{ return TK_TRUE; }
#line 1977 "lua-parser.re2c.c"
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy204;
	default:	goto yy48;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy206;
	default:	goto yy48;
	}
yy192:
	++YYCURSOR;
#line 110 "lua-parser.re2c"
	{ return TK_LABEL; }
#line 1994 "lua-parser.re2c.c"
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy195;
	}
yy195:
#line 66 "lua-parser.re2c"
	{ return TK_BREAK; }
#line 2066 "lua-parser.re2c.c"
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy208;
	default:	goto yy48;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy198;
	}
yy198:
#line 71 "lua-parser.re2c"
	{ return TK_FALSE; }
#line 2144 "lua-parser.re2c.c"
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy210;
	default:	goto yy48;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy201;
	}
yy201:
#line 77 "lua-parser.re2c"
	{ return TK_LOCAL; }
#line 2222 "lua-parser.re2c.c"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy211;
	default:	goto yy48;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy213;
	default:	goto yy48;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy205;
	}
yy205:
#line 85 "lua-parser.re2c"
	{ return TK_UNTIL; }
#line 2306 "lua-parser.re2c.c"
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy207;
	}
yy207:
#line 86 "lua-parser.re2c"
	{ return TK_WHILE; }
#line 2378 "lua-parser.re2c.c"
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy209;
	}
yy209:
#line 69 "lua-parser.re2c"
	{ return TK_ELSEIF; }
#line 2450 "lua-parser.re2c.c"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy215;
	default:	goto yy48;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy212;
	}
yy212:
#line 81 "lua-parser.re2c"
	{ return TK_REPEAT; }
#line 2528 "lua-parser.re2c.c"
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy214;
	}
yy214:
#line 82 "lua-parser.re2c"
	{ return TK_RETURN; }
#line 2600 "lua-parser.re2c.c"
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy216;
	default:	goto yy48;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy217;
	}
yy217:
#line 73 "lua-parser.re2c"
	{ return TK_FUNCTION; }
#line 2678 "lua-parser.re2c.c"
}
#line 153 "lua-parser.re2c"


LongString:
  long_top = s->cur;


#line 2687 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy220;
	case '\n':	goto yy224;
	case '[':	goto yy226;
	case ']':	goto yy227;
	default:	goto yy222;
	}
yy220:
	++YYCURSOR;
#line 167 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long string at line %d\n", long_start_line); exit(1);}
#line 2702 "lua-parser.re2c.c"
yy222:
	++YYCURSOR;
yy223:
#line 166 "lua-parser.re2c"
	{ goto LongString; }
#line 2708 "lua-parser.re2c.c"
yy224:
	++YYCURSOR;
#line 164 "lua-parser.re2c"
	{ processNewLine(s); goto LongString; }
#line 2713 "lua-parser.re2c.c"
yy226:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy228;
	case '[':	goto yy231;
	default:	goto yy223;
	}
yy227:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy233;
	case ']':	goto yy235;
	default:	goto yy223;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy228;
	case '[':	goto yy231;
	default:	goto yy230;
	}
yy230:
	YYCURSOR = YYMARKER;
	goto yy223;
yy231:
	++YYCURSOR;
#line 160 "lua-parser.re2c"
	{ int qsz = (int)(s->cur - long_top); if(qsz == quote_size) nest_count++; goto LongString; }
#line 2742 "lua-parser.re2c.c"
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy233;
	case ']':	goto yy235;
	default:	goto yy230;
	}
yy235:
	++YYCURSOR;
	YYCURSOR -= 1;
#line 161 "lua-parser.re2c"
	{ int qsz = (int)(s->cur+1 - long_top); if( (nest_count == 0) && (qsz == quote_size)) { ++s->cur; return TK_LONGSTRING; };
                          if(qsz == quote_size) nest_count--; goto LongString; }
#line 2756 "lua-parser.re2c.c"
}
#line 169 "lua-parser.re2c"


Comment:


#line 2764 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy240;
	case '\n':	goto yy239;
	default:	goto yy242;
	}
yy239:
#line 175 "lua-parser.re2c"
	{ return TK_COMMENT; }
#line 2776 "lua-parser.re2c.c"
yy240:
	++YYCURSOR;
#line 176 "lua-parser.re2c"
	{ goto regular; }
#line 2781 "lua-parser.re2c.c"
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy239;
	default:	goto yy242;
	}
}
#line 178 "lua-parser.re2c"


LongComment:
  long_top = s->cur;


#line 2797 "lua-parser.re2c.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy246;
	case '\n':	goto yy250;
	case '[':	goto yy252;
	case ']':	goto yy253;
	default:	goto yy248;
	}
yy246:
	++YYCURSOR;
#line 191 "lua-parser.re2c"
	{ fprintf(stderr, "unfinished long comment at line %d\n", long_start_line); exit(1);}
#line 2812 "lua-parser.re2c.c"
yy248:
	++YYCURSOR;
yy249:
#line 190 "lua-parser.re2c"
	{ goto LongComment; }
#line 2818 "lua-parser.re2c.c"
yy250:
	++YYCURSOR;
#line 189 "lua-parser.re2c"
	{ processNewLine(s); goto LongComment; }
#line 2823 "lua-parser.re2c.c"
yy252:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy254;
	case '[':	goto yy257;
	default:	goto yy249;
	}
yy253:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy259;
	case ']':	goto yy261;
	default:	goto yy249;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy254;
	case '[':	goto yy257;
	default:	goto yy256;
	}
yy256:
	YYCURSOR = YYMARKER;
	goto yy249;
yy257:
	++YYCURSOR;
#line 185 "lua-parser.re2c"
	{ int qsz = (int)(s->cur - long_top); if(qsz == quote_size) nest_count++; goto LongComment; }
#line 2852 "lua-parser.re2c.c"
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy259;
	case ']':	goto yy261;
	default:	goto yy256;
	}
yy261:
	++YYCURSOR;
	YYCURSOR -= 1;
#line 186 "lua-parser.re2c"
	{ int qsz = (int)(s->cur+1 - long_top); if( (nest_count == 0) && (qsz == quote_size)) { ++s->cur; return TK_LONGCOMMENT; };
                          if(qsz == quote_size) nest_count--; goto LongComment; }
#line 2866 "lua-parser.re2c.c"
}
#line 193 "lua-parser.re2c"


  fprintf(stderr, "impossible"); exit(1);/* die */
}

static LuaParserToken *pushToken(LuaParserState *pState, LuaScanner *scanner, int token_id) {
  LuaParserToken* token_value = malloc(sizeof(*token_value));
  token_value->flags = 0;
  token_value->token_id = token_id;
  if(scanner->last_top != scanner->top) {
    token_value->space_before_size = (int)(scanner->top - scanner->last_top);
    token_value->space_before_pos = (int)(scanner->last_top - pState->src);
  }
  else {
    token_value->space_before_size = 0;
    token_value->space_before_pos = 0;
  }
  scanner->last_top = scanner->cur;
  token_value->token_value_size = (int)(scanner->cur - scanner->top);
  token_value->token_value =  scanner->top;
  pushLuaParserToken(pState, token_value);
  return token_value;
}

int main(int argc, char *argv[]) {

  FILE *fp, *traceFile;
  long size;
  char *buff, *buff_end;
  size_t bytes;
  int token;
  LuaScanner scanner;
  LuaParserState parser_state;
  void *parser;
  //ParserCount pCount;
  
  int fn_argc = 1;
  int noToCompound = 0;
  if(argc > 2) {
    if (strcmp(argv[1] , "-nc") == 0) noToCompound = 1;
    else {
      printf("usage : %s [options] lua_fname\n\toptions:\n\t\t-nc\tdo not convert to compound assginments\n", argv[0]);
      exit(1);
    }
    fn_argc = 2;
  }

  /* Open input file */
  const char *fname = "test.lua";
  if(argc > 1) fname = argv[fn_argc];
  fp = fopen(fname, "r");
  if(fp == NULL) {
    fprintf(stderr, "Can't open test file\n");
    exit(-1);
  }

  /* Open trace file */
  traceFile = fopen("trace.out", "w");
  if(traceFile == NULL) {
    fprintf(stderr, "Can't open trace file\n");
    exit(-1);
  }

  /* Get file size */
  fseek(fp, 0, SEEK_END);
  size = ftell(fp);
  rewind(fp);

  /*We only manage sources smaller than INT_MAX size */
  if(size > INT_MAX) {
    printf("Error file size bigger than %d\n", INT_MAX);
    exit(1);
  }

  /*
  * Allocate buffer and read, +2 just in case file do not end in '\n'
  */
  buff = (char*) malloc((size+2) * sizeof(char));
  bytes = fread(buff, 1, size, fp);
  if (bytes != size) {
    fprintf(stderr, "Error reading input file\n");
    exit(-1);
  }
  buff[size] = '\0';
  
  if(size > 1 && buff[size-1] != '\n') {
    /* to make things easy to parse we need a '\n' at the end */
    buff[size] = '\n';
    buff[size+1] = '\0';
    ++size;
  }

  /* Initialize scanner */
  scanner.line = 1;
  scanner.top = scanner.last_top = buff;
  scanner.cur = buff;
  scanner.pos = buff;
  scanner.ptr = buff;
  scanner.limit = buff+size;

  /* Initialize parser state */
  initializeLuaParserState(&parser_state);
  parser_state.src = buff;
  parser_state.noToCompound = noToCompound;

  /* Initialize the parser state structure */
  //pCount.numFunctionDefinitions = 0;
  //pCount.numVariableDeclarations = 0;

  /* Pointer to the end of the buffer */
  buff_end = (char*) (((char*)buff) + size);

  /* Create parser and set up tracing */
  parser = LuaParserAlloc(malloc);
#ifndef NDEBUG
  LuaParserTrace(traceFile, "parser >> ");
#endif

  //printf("%d:%d:%d:%d\n", TK_SPACE, TK_COMMENT, TK_LONGCOMMENT, TK_THEEND);
  while((token = scan(&scanner, buff_end))) {
    if(token != TK_THEEND) {
      LuaParserToken *token_value = pushToken(&parser_state, &scanner, token);

      if(token < TK_LEMON_LAST_TOKEN) {
        LuaParser(parser, token, token_value, &parser_state);
      }
      else //SpecialTokens
      {
        //size_t gap_length = scanner.cur - scanner.top;
        switch(token) {
          case TK_SPACE:
            //printf("=S=%.*s=S=\n", (int)gap_length, scanner.top);
          break;
          case TK_COMMENT:
            //printf("=C=%.*s=C=\n", (int)gap_length, scanner.top);
            newStrFmt(token_value, "//%.*s", token_value->token_value_size-2, token_value->token_value+2);
          break;
          case TK_LONGCOMMENT: {
            //printf("=LC=%.*s=LC=\n", (int)gap_length, scanner.top);
            int quote_end = 4; // "--[["
            while(token_value->token_value[quote_end-1] != '[') ++quote_end; //try to find the end
            newStrFmt(token_value, "/*%.*s*/", token_value->token_value_size - quote_end - (quote_end-2), // -2 for "--"
                                                                  token_value->token_value + quote_end);
          }
          break;
        }
      }
    }
    else {
      if(scanner.last_top < buff_end) pushToken(&parser_state, &scanner, TK_SPACE);
      // Execute Parse for the last time
      LuaParser(parser, 0, NULL, &parser_state);
      break;
    }
  }
  /* Print results of parsing */
  //printf("Number of function definitions: %d.\n", pCount.numFunctionDefinitions);
  //printf("Number of variable declarations: %d.\n", pCount.numVariableDeclarations);

  /* output the reconstruction */
  doOutput(&parser_state);

  /* Deallocate parser */
  LuaParserFree(parser, free);
  
  resetLuaParserState(&parser_state);

  /* Close files and deallocate */
  fclose(fp);
  fclose(traceFile);
  free(buff);
  return(0);
}
